### ISSUE TITLE
Stack implementation

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [Abhijit2505/Algorithmic-Treasure-Original#12]
I want to implement all the functions of stack
- Push
- Pop
- Top
- IsEmpty
- IsFull

**Comment by Rishikeshrajrxl** [comment]
I will implement this in c++, please assign me

**Comment by Masters-Akt** [comment]
Please assign me this issue, I will do it in C language.

**Comment by subhangi2731** [comment]
can you please assign me the issue

**Comment by Abhijit2505** [comment]
Please open-up this issue once SWoC begins.
