### ISSUE TITLE
Queue implementation

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [Abhijit2505/Algorithmic-Treasure-Original#13]
I will implement functions such as
- Front
- Pop
- Push
- IsFull
- IsEmpty

**Comment by Rishikeshrajrxl** [comment]
Please Assign me this issue, I will do this in C++

**Comment by Masters-Akt** [comment]
Please assign me this issue, I will do it in C language.

**Comment by subhangi2731** [comment]
can you please assign me this? I will do it in python

**Comment by Abhijit2505** [comment]
Please open up this issue once SWOC begins on 5th Jan 2021
