### ISSUE TITLE
Each click opens a new window

### ISSUE THREAD

**Issue by abhijeet007rocks8** [Abhijit2505/Algorithmic-Treasure-Original#14]
Issue-
On Each Click a new tab opens up which ends up opening too many tabs and causes confusion.

Solution-
The new page should open up on the tab and on pressing back button it should navigate back to previous page.

I would like too work on this issue under SWOC2021, so please it would be huge help if you could assign this issue to me.
Thank You.

**Comment by Abhijit2505** [comment]
Please open up the same issue after 5th Jan 2021, when SWoC begins
