### ISSUE TITLE
adding different algorithms

### ISSUE THREAD

**Issue by nitya123-github** [Abhijit2505/Algorithmic-Treasure-Original#16]
can i add a different code snippets  related to strings and also different sorting and searching algorithms 

And  can i work this for swoc?

**Comment by amandp13** [comment]
@Abhijit2505  Can you please assign this issue to me as a SWOC 2021 participant?

**Comment by Utkarsh-Agarwal-585** [comment]
@Abhijit2505 I'm ready to work on this. Can you assign it to me .

**Comment by ayushi-get** [comment]
i would love to work on this issue @Abhijit2505 ,i am also a participant of SWOC.

**Comment by lavishabhambri** [comment]
@Abhijit2505 I am willing to work on this issue and I am a participant of SWOC. Kindly, please assign me this issue.

**Comment by ishikalohia** [comment]
I am looking forward working on this issue. Can you please assign it to me. I am participant of SWOC21

**Comment by Priyaraj17** [comment]
I am very interested on working on this issue, Can you please assign it to me. I am a participant of SWOC21.

**Comment by nporia** [comment]
I would like to work on this issue too as a participant of SWOC'21.

**Comment by Abhijit2505** [comment]
Don't create such abstract issues, create an issue which states a problem instead of an algorithm.

We provide solutions to the problems on the site.
