### ISSUE TITLE
Participated Opensource Programs Section

### ISSUE THREAD

**Issue by aniketsingh98571** [Abhijit2505/Algorithmic-Treasure-Original#19]
![Screenshot (42)](https://user-images.githubusercontent.com/63097956/103608271-fd3bfb80-4f40-11eb-9fe9-bb62d195c406.png)

Under the Dark theme, the current ` BWLU(Build With LetsUpgrade) [July,20 - Sept,20]` Logo is not visible, and also I am trying to add `SWoC` also in the 'Participated Opensource Programs section' with its logo which is mentioned below.
1.BWLU
![Build with lets upgrade](https://user-images.githubusercontent.com/63097956/103608405-4e4bef80-4f41-11eb-8d38-3a4e11d76565.png)

2.SWoC
![SWOC](https://user-images.githubusercontent.com/63097956/103608420-54da6700-4f41-11eb-9d7e-dfdaf074147a.jpg)

**Comment by aniketsingh98571** [comment]
@Abhijit2505 I am willing to solve this issue for SWoC[Script Winter of Code].Please assign me the issue.

**Comment by Abhijit2505** [comment]
This is not an issue and something which we are not accepting from the contributors.

Don't try to create any issues related to the change in the README file.

Hence closing the issue.
