### ISSUE TITLE
Spelling mistake in documentation page

### ISSUE THREAD

**Issue by Priyaraj17** [Abhijit2505/Algorithmic-Treasure-Original#20]
I want to correct the spelling mistake in the heading titled '**Probelm Section**'. 
Here is the image:
![Screenshot from 2021-01-05 12-08-55](https://user-images.githubusercontent.com/40101776/103614777-675b9d00-4f4f-11eb-8c49-6cbd25019cc3.png)

I would like to work on this issue.

**Comment by nporia** [comment]
I would like to work on it.

**Comment by nporia** [comment]
I would like to work on this issue too as a participant of SWOC.

**Comment by ishika172** [comment]
Please assign me this issue for Swoc.

**Comment by Abhijit2505** [comment]
@Priyaraj17 please solve it, also check for other spelling mistakes.
