### ISSUE TITLE
Dynamic Programming algorithms

### ISSUE THREAD

**Issue by Priyaraj17** [Abhijit2505/Algorithmic-Treasure-Original#22]
I would like to work on dynamic programming algorithms. I can provide all the important algorithms such as knapsack, coin change, staircase, etc.  Please assign this issue to me as a SWOC 2021 participant.

**Comment by Abhijit2505** [comment]
Please don't consume an entire programming department for your issue.

And the most important thing, we add problems, their solutions and explanations, please create an issue which has only one problem stated.

Hence closing the issue.
