### ISSUE TITLE
Few Writing Mistakes in the documentation page.

### ISSUE THREAD

**Issue by nporia** [Abhijit2505/Algorithmic-Treasure-Original#24]
-The p of problem statement on the left sidebar should be capital.
-Similarly h of hashmaps.
-In the footer it is written "We welcome every C++ & python lover to come forwards " , forwads should be corrected to forward and "Keep coding, keep loving python & ++", ++ should be corrected to C++.

![image](https://user-images.githubusercontent.com/20817990/103623118-a7c21780-4f5d-11eb-8c9b-e294e70f065c.png)
![image](https://user-images.githubusercontent.com/20817990/103623443-2d45c780-4f5e-11eb-9c18-0499c1a9a7dc.png)

I would like to work on this issue . Please assign me for the same.

**Comment by ishika172** [comment]
Can I take up the work for Swoc?

**Comment by Abhijit2505** [comment]
@nporia please start working.

**Comment by nporia** [comment]
I made the PR sir.
