### ISSUE TITLE
One Dimensional Array -> Maximum Absolute Difference : Add C++ code and fix some bugs

### ISSUE THREAD

**Issue by rashigupta01** [Abhijit2505/Algorithmic-Treasure-Original#25]
Hello @Abhijit2505 !
I am Rashi, a Participant of SWOC'21. I have found a few issues on the page - Maximum Absolute Difference in the section One Dimensional Array and would like to work on them. 
Link to the page - https://abhijit2505.github.io/Algorithmic-Treasure-Site/Pages/Array/maxAbsoluteDiff.html

Following are the issues:

1) Only Python code is available for this problem. I would like to add C++ code as well and add its tag at the top.
![image](https://user-images.githubusercontent.com/65219981/103651853-33e93480-4f88-11eb-993b-747fe566d61b.png)

2) The title has been mistyped as **Adding One to Number** instead of **Maximum Absolute Difference**
![image](https://user-images.githubusercontent.com/65219981/103652107-9d694300-4f88-11eb-81b1-db1849308c73.png)

3) The four cases are not at all clear. 
![image](https://user-images.githubusercontent.com/65219981/103652227-cc7fb480-4f88-11eb-9fae-88a1f19acb90.png)

4) There is error in Python code.
![image](https://user-images.githubusercontent.com/65219981/103652402-149ed700-4f89-11eb-9a37-82843e38d7f5.png)

Please assign this issue to me, would like to work on them.

**Comment by Rishikeshrajrxl** [comment]
I can do this in C++ , Java

**Comment by Abhijit2505** [comment]
@rashigupta01 please get started.
