### ISSUE TITLE
Implementation of important algorithms using stack data structure in python

### ISSUE THREAD

**Issue by spursbyte** [Abhijit2505/Algorithmic-Treasure-Original#26]
stacks are important data structure and there are a few examples of stack implementation in the repo. Let me update the repo with the same .so please assign me the issue. some important stack implemetations include 2stack implementation, The celebrity problem,arithmetic expression evaluation etc. I am a participant in swoc21

**Comment by Abhijit2505** [comment]
Please choose one problem statement and create an issue for the same.
Don't create an issue stating an entire programming DS department like a stack.

Just state one problem statement.

Closing the issue.
