### ISSUE TITLE
Page redirected to the same page

### ISSUE THREAD

**Issue by rounaksarda** [Abhijit2505/Algorithmic-Treasure-Original#29]
@Abhijit2505 From SWOC2021, As I was visiting the webpage I found we do not have programs for 1> Mathematic problems, 2>Hashmap and 3> OOP design.

I want to work on these topics. If we can discuss, do let me know how can I get going to add interesting program for above mentioned topics

**Comment by Abhijit2505** [comment]
Well, we know we have no problems on these sections, if you want to add problems, please make an issue stating the problems.

Don't create an issue setting a department of problems like Hashmap or OOP Designing.
