### ISSUE TITLE
Binary search way of solving painters partition problem

### ISSUE THREAD

**Issue by vaishnavijha** [Abhijit2505/Algorithmic-Treasure-Original#30]
Painters partition problem is a very famous problem of DP . But it can be solved easily using binary search algorithm.
link for problem : https://www.interviewbit.com/problems/painters-partition-problem/

**Comment by vaishnavijha** [comment]
I want to work on this issue if it is seen as good contribution to add .Can i be assigned this issue .Please review.

**Comment by Abhijit2505** [comment]
@vaishnavijha please get started.

**Comment by vaishnavijha** [comment]
Please check the pull request raised to this issue
