### ISSUE TITLE
Improving documentation section

### ISSUE THREAD

**Issue by sakshikhachane** [Abhijit2505/Algorithmic-Treasure-Original#31]
Description -
The buttons in the documentation section can be aligned and by hovering on them we can give some brief info. For example on hovering one-dimensional array, we can add what a one-dimensional array is. Else the second idea could be to make two buttons for which one button will give the info and the second will redirect to problems.

@Abhijit2505 I am a participant in SWOC. I would like to work on this issue if you liked this idea. Kindly assign this to me.

**Comment by Abhijit2505** [comment]
@sakshikhachane please get started with the issue.
