### ISSUE TITLE
Adding question in One Dimensional Array 

### ISSUE THREAD

**Issue by Saviour1001** [Abhijit2505/Algorithmic-Treasure-Original#32]
I want to add the question of the maximum sum of a subarray in the database of One Dimensional array. Link to the question https://leetcode.com/problems/maximum-subarray/

**Comment by Abhijit2505** [comment]
@Saviour1001 please get started.

**Comment by sammy8825** [comment]
Can i work on this issue @Abhijit2505 if @Saviour1001 is not working on it.

**Comment by Saviour1001** [comment]
@sammy8825 I am sorry but right now my exams are going on at the moment and thus I am focussed on them. I will finish this soon.

**Comment by fatmab2809** [comment]
Can I work on this issue?

**Comment by Saviour1001** [comment]
Created a pull request #75 to solve the issue
