### ISSUE TITLE
Remove duplicate elements from sorted Array 

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [Abhijit2505/Algorithmic-Treasure-Original#34]
Input:
N = 3
Array = {1, 2, 2}
Output: 1 2

**Comment by Rishikeshrajrxl** [comment]
Assign me this issue under SWOC, please

**Comment by Abhijit2505** [comment]
This is already present in the site.

Warning - Please create issues which are not present in the website, or else you will be banned.
