### ISSUE TITLE
Finding the majority? 

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [Abhijit2505/Algorithmic-Treasure-Original#35]
Given an array of size N and two elements x and y, use counter variables to find which element appears most in the array, x or y. If both elements have the same frequency, then return the smaller element.

Input:
N = 11
arr[] = {1,1,2,2,3,3,4,4,4,4,5}
x = 4, y = 5
Output: 4
Explanation: 
frequency of 4 is 4.
frequency of 5 is 1.

**Comment by Rishikeshrajrxl** [comment]
Assign me this issue under SWOC.

**Comment by Abhijit2505** [comment]
Similar questions are present and this problem can be achieved easily from those problems.
