### ISSUE TITLE
Implementation of FCFS CPU Scheduling Algorithm.

### ISSUE THREAD

**Issue by amandp13** [Abhijit2505/Algorithmic-Treasure-Original#43]
- First Come First Serve (FCFS) is an operating system scheduling algorithm that automatically executes queued requests and processes in order of their arrival.

**Comment by chehak123** [comment]
I would like to work on this under SWOC

**Comment by amandp13** [comment]
@chehak123 Actually I am working on this issue, You can work on another one.

**Comment by Abhijit2505** [comment]
@amandp13, as discussed earlier in the Slack, we are not interested in adding algorithms to the site but the problems. Please mention the problems, not the algorithms.
