### ISSUE TITLE
stack Implementation

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [Abhijit2505/Algorithmic-Treasure-Original#50]
I want to implement all the functions of stack

-  Push
- Pop
 - Top
- IsEmpty
- IsFull

**Comment by Rishikeshrajrxl** [comment]
do assign me this issue under SWOC .

**Comment by Rishikeshrajrxl** [comment]
@Abhijit2505 assign me this isue

**Comment by Neha62-lit** [comment]
@Abhijit2505 can you assign me this issue?? I would be like to implement the stack and work on this issue!!
