### ISSUE TITLE
Finding max subarray sum

### ISSUE THREAD

**Issue by ms1901** [Abhijit2505/Algorithmic-Treasure-Original#56]
I would like to add a problem to find the maximum subarray sum.
Input is: [-2,1,-3,4,-1,2,1,-5,4]
Output is 6 ,as [4,-1,2,1] has the largest sum = 6
I would like to work on this issue for SWOC'21. 
Problem link:https://leetcode.com/problems/maximum-subarray/

**Comment by japneetbhatia** [comment]
Hey! Please assign this to me for SWOC

**Comment by Neha62-lit** [comment]
I would like to work on this issue. Please assigned to me.

**Comment by Abhijit2505** [comment]
@ms1901 please get started.

**Comment by Saviour1001** [comment]
@ms1901 I have already added this question, I did raise the issue earlier and generated the PR. #75

**Comment by ms1901** [comment]
@Abhijit2505 could you please clarify If I can continue to work towards this question?
