### ISSUE TITLE
Find Kth smallest element in a row-column sorted matrix. Explaination and Implementation in C++

### ISSUE THREAD

**Issue by yashgupta18** [Abhijit2505/Algorithmic-Treasure-Original#57]
Q. Find Kth smallest element in a row-column sorted matrix
Difficulty: hard
Input: matrix, k
output: kth smallest element from the matrix

**Comment by yashgupta18** [comment]
Please assign me this issue under SWOC

**Comment by subhangi2731** [comment]
please assign me issue

**Comment by Abhijit2505** [comment]
@yashgupta18 please get started

**Comment by yashgupta18** [comment]
@Abhijit2505  Sure thanks.
