### ISSUE TITLE
Add Questions on String 

### ISSUE THREAD

**Issue by uditphoolwani** [Abhijit2505/Algorithmic-Treasure-Original#59]
As this project aims to build a website which will contain the codes along with the techniques and explanations so that it can be helpful for students preparing for an interview and. The string is one of the important topics for interview preparation, so I want to add questions of String.

> 

> 

@Abhijit2505 Sir,Please assign me this issue under **SWOC**.

**Comment by Abhijit2505** [comment]
Don't create an issue with some *algorithm*, just mention the specific problem you want to work with.
