### ISSUE TITLE
Spiral Display of elements of  2-D array

### ISSUE THREAD

**Issue by japneetbhatia** [Abhijit2505/Algorithmic-Treasure-Original#60]
Suppose the array is :
11 12 13 14 15
21 22 23 24 25
31 32 33 34 35
Output :
11 21 31 32 33 34 35 25 15 14 13 12 22 23 24

**Comment by japneetbhatia** [comment]
I want to work under this issue please assign this to me for SWOC

**Comment by Abhijit2505** [comment]
@japneetbhatia please get started

**Comment by nayaldivya** [comment]
Hi @Abhijit2505, Output mentioned above is printing the result in anticlockwise manner, may i also work on this issue and solve it the other way (i.e. in clockwise direction)
