### ISSUE TITLE
Find Permutations of a given string(recursion)(c++)

### ISSUE THREAD

**Issue by muskan-888** [Abhijit2505/Algorithmic-Treasure-Original#66]
For a given string say abc. It will print all the possible permutations. That are:
abc
acb
bac
bca
cab
cba

**Comment by muskan-888** [comment]
I can work on this issue and solve it using c++.

**Comment by Abhijit2505** [comment]
@muskan-888 please get started.

**Comment by vilsi12** [comment]
can i work on issue using python
